export interface CourseCatalogEntry {
  code: string;
  title: string;
  gradeLevel: number;
  keywords?: readonly string[];
}

export const COURSE_PLAN_CATALOG: readonly CourseCatalogEntry[] = [
  { code: 'ENG1D', title: 'English', gradeLevel: 9, keywords: ['literacy', 'language arts'] },
  { code: 'ENL1W', title: 'English', gradeLevel: 9, keywords: ['english'] },
  { code: 'MPM1D', title: 'Principles of Mathematics', gradeLevel: 9, keywords: ['math', 'algebra'] },
  { code: 'MTH1W', title: 'Mathematics', gradeLevel: 9, keywords: ['math', 'algebra'] },
  { code: 'SNC1D', title: 'Science', gradeLevel: 9, keywords: ['science'] },
  { code: 'CGC1D', title: 'Geography of Canada', gradeLevel: 9, keywords: ['geography'] },
  { code: 'FSF1D', title: 'Core French', gradeLevel: 9, keywords: ['french'] },
  { code: 'BTT1O', title: 'Information and Communication Technology', gradeLevel: 9, keywords: ['computer', 'technology'] },
  { code: 'PPL1O', title: 'Healthy Active Living', gradeLevel: 9, keywords: ['pe', 'health'] },
  { code: 'AMU1O', title: 'Music', gradeLevel: 9, keywords: ['music', 'instrumental'] },
  { code: 'AVI1O', title: 'Visual Arts', gradeLevel: 9, keywords: ['art', 'design'] },
  { code: 'ENG2D', title: 'English', gradeLevel: 10, keywords: ['literacy', 'language arts'] },
  { code: 'MPM2D', title: 'Principles of Mathematics', gradeLevel: 10, keywords: ['math', 'algebra'] },
  { code: 'MFM2P', title: 'Foundations of Mathematics', gradeLevel: 10, keywords: ['math'] },
  { code: 'SNC2D', title: 'Science', gradeLevel: 10, keywords: ['science'] },
  { code: 'CHC2D', title: 'Canadian History Since World War I', gradeLevel: 10, keywords: ['history', 'canada'] },
  { code: 'CHV2O', title: 'Civics', gradeLevel: 10, keywords: ['civics', 'citizenship'] },
  { code: 'GLC2O', title: 'Career Studies', gradeLevel: 10, keywords: ['career', 'guidance'] },
  { code: 'FSF2D', title: 'Core French', gradeLevel: 10, keywords: ['french'] },
  { code: 'BBI2O', title: 'Introduction to Business', gradeLevel: 10, keywords: ['business'] },
  { code: 'ICS2O', title: 'Introduction to Computer Studies', gradeLevel: 10, keywords: ['computer', 'coding'] },
  { code: 'ENG3U', title: 'English', gradeLevel: 11, keywords: ['literacy', 'language arts'] },
  { code: 'MCR3U', title: 'Functions', gradeLevel: 11, keywords: ['math', 'functions'] },
  { code: 'MCF3M', title: 'Functions and Applications', gradeLevel: 11, keywords: ['math', 'functions'] },
  { code: 'MBF3C', title: 'Foundations for College Mathematics', gradeLevel: 11, keywords: ['math'] },
  { code: 'SCH3U', title: 'Chemistry', gradeLevel: 11, keywords: ['chemistry', 'science'] },
  { code: 'SBI3U', title: 'Biology', gradeLevel: 11, keywords: ['biology', 'science'] },
  { code: 'SPH3U', title: 'Physics', gradeLevel: 11, keywords: ['physics', 'science'] },
  { code: 'BAF3M', title: 'Financial Accounting Fundamentals', gradeLevel: 11, keywords: ['accounting', 'business'] },
  { code: 'ICS3U', title: 'Introduction to Computer Science', gradeLevel: 11, keywords: ['computer', 'coding'] },
  { code: 'HRT3M', title: 'World Religions', gradeLevel: 11, keywords: ['religion', 'humanities'] },
  { code: 'TGJ3M', title: 'Communications Technology', gradeLevel: 11, keywords: ['media', 'technology'] },
  { code: 'ENG4U', title: 'English', gradeLevel: 12, keywords: ['literacy', 'language arts'] },
  { code: 'MHF4U', title: 'Advanced Functions', gradeLevel: 12, keywords: ['math', 'functions'] },
  { code: 'MCV4U', title: 'Calculus and Vectors', gradeLevel: 12, keywords: ['math', 'calculus'] },
  { code: 'MAP4C', title: 'Foundations for College Mathematics', gradeLevel: 12, keywords: ['math'] },
  { code: 'SCH4U', title: 'Chemistry', gradeLevel: 12, keywords: ['chemistry', 'science'] },
  { code: 'SBI4U', title: 'Biology', gradeLevel: 12, keywords: ['biology', 'science'] },
  { code: 'SPH4U', title: 'Physics', gradeLevel: 12, keywords: ['physics', 'science'] },
  { code: 'BBB4M', title: 'International Business Fundamentals', gradeLevel: 12, keywords: ['business'] },
  { code: 'BOH4M', title: 'Business Leadership', gradeLevel: 12, keywords: ['business', 'leadership'] },
  { code: 'HSB4U', title: 'Challenge and Change in Society', gradeLevel: 12, keywords: ['society', 'social science'] },
  { code: 'ICS4U', title: 'Computer Science', gradeLevel: 12, keywords: ['computer', 'coding'] },
  { code: 'ADA4M', title: 'Drama', gradeLevel: 12, keywords: ['drama', 'arts'] },
  { code: 'AMU4M', title: 'Music', gradeLevel: 12, keywords: ['music', 'instrumental'] },
];
