export type ProvinceFilterCountry = 'Canada' | 'China (mainland)' | 'United States';

export const COUNTRY_FILTER_ALL_OPTION = 'All';
export const COUNTRY_FILTER_NA_OPTION = 'N/A';
export const COUNTRY_FILTER_PRIORITY_OPTIONS = ['Canada', 'China (mainland)', 'United States'] as const;

export const PROVINCE_FILTER_COUNTRIES: readonly ProvinceFilterCountry[] = [
  'Canada',
  'China (mainland)',
  'United States',
];

export const COUNTRY_FILTER_FALLBACK_OPTIONS = [
  'United Kingdom',
  'Australia',
  'New Zealand',
  'Japan',
  'South Korea',
  'Singapore',
  'India',
  'France',
  'Germany',
  'Italy',
  'Spain',
  'Netherlands',
  'Switzerland',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Ireland',
  'Belgium',
  'Austria',
  'Portugal',
  'Mexico',
  'Brazil',
  'Argentina',
  'Chile',
  'South Africa',
  'Egypt',
  'Saudi Arabia',
  'United Arab Emirates',
] as const;

export const PROVINCE_FILTER_OPTIONS_BY_COUNTRY: Record<ProvinceFilterCountry, readonly string[]> = {
  Canada: [
    'Ontario',
    'British Columbia',
    'Alberta',
    'Quebec',
    'Manitoba',
    'Saskatchewan',
    'New Brunswick',
    'Nova Scotia',
    'Newfoundland and Labrador',
    'Prince Edward Island',
    'Northwest Territories',
    'Nunavut',
    'Yukon',
  ],
  'China (mainland)': [
    'Anhui',
    'Beijing',
    'Chongqing',
    'Fujian',
    'Gansu',
    'Guangdong',
    'Guangxi',
    'Guizhou',
    'Hainan',
    'Hebei',
    'Heilongjiang',
    'Henan',
    'Hong Kong',
    'Hubei',
    'Hunan',
    'Inner Mongolia',
    'Jiangsu',
    'Jiangxi',
    'Jilin',
    'Liaoning',
    'Macao',
    'Ningxia',
    'Qinghai',
    'Shaanxi',
    'Shandong',
    'Shanghai',
    'Shanxi',
    'Sichuan',
    'Taiwan',
    'Tianjin',
    'Tibet',
    'Xinjiang',
    'Yunnan',
    'Zhejiang',
  ],
  'United States': [
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'District of Columbia',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming',
  ],
};

export const CITY_FILTER_OPTIONS_BY_COUNTRY: Record<ProvinceFilterCountry, readonly string[]> = {
  Canada: [
    'Toronto',
    'Montreal',
    'Vancouver',
    'Calgary',
    'Ottawa',
    'Edmonton',
    'Winnipeg',
    'Quebec City',
    'Halifax',
    'Mississauga',
    'Hamilton',
    'Kitchener',
    'London',
    'Victoria',
    'Oshawa',
    'Windsor',
    'Saskatoon',
    'Regina',
    "St. John's",
    'Barrie',
    'Kelowna',
    'Sherbrooke',
    'Guelph',
    'Thunder Bay',
    'Moncton',
    'Brantford',
    'Saint John',
    'Red Deer',
    'Kamloops',
    'Lethbridge',
    'Nanaimo',
    'Peterborough',
    'Kingston',
    'Chilliwack',
    'Sarnia',
    'Sudbury',
    'Prince George',
    'Trois-Rivieres',
    'Medicine Hat',
    'Fredericton',
    'Whitehorse',
    'Yellowknife',
    'Iqaluit',
    'Brampton',
    'Surrey',
    'Laval',
    'Burnaby',
    'Richmond',
    'Markham',
    'Vaughan',
  ],
  'China (mainland)': [
    'Beijing',
    'Shanghai',
    'Guangzhou',
    'Shenzhen',
    'Chengdu',
    'Hangzhou',
    'Wuhan',
    'Chongqing',
    'Nanjing',
    'Tianjin',
    "Xi'an",
    'Suzhou',
    'Qingdao',
    'Ningbo',
    'Zhengzhou',
    'Changsha',
    'Dongguan',
    'Foshan',
    'Shenyang',
    'Dalian',
    'Harbin',
    'Jinan',
    'Xiamen',
    'Fuzhou',
    'Kunming',
    'Hefei',
    'Nanchang',
    'Taiyuan',
    'Urumqi',
    'Lanzhou',
    'Guiyang',
    'Nanning',
    'Hohhot',
    'Haikou',
    'Shijiazhuang',
    'Wuxi',
    'Nantong',
    'Changzhou',
    'Wenzhou',
    'Yantai',
    'Zhuhai',
    'Huizhou',
    'Quanzhou',
    'Yinchuan',
    'Xining',
    'Lhasa',
    'Jilin',
    'Luoyang',
    'Weifang',
    'Baoding',
  ],
  'United States': [
    'New York',
    'Los Angeles',
    'Chicago',
    'Houston',
    'Phoenix',
    'Philadelphia',
    'San Antonio',
    'San Diego',
    'Dallas',
    'San Jose',
    'Seattle',
    'Boston',
    'Washington',
    'Austin',
    'Jacksonville',
    'Fort Worth',
    'Columbus',
    'Charlotte',
    'San Francisco',
    'Indianapolis',
    'Denver',
    'El Paso',
    'Nashville',
    'Detroit',
    'Oklahoma City',
    'Portland',
    'Las Vegas',
    'Memphis',
    'Louisville',
    'Baltimore',
    'Milwaukee',
    'Albuquerque',
    'Tucson',
    'Fresno',
    'Sacramento',
    'Mesa',
    'Kansas City',
    'Atlanta',
    'Omaha',
    'Colorado Springs',
    'Raleigh',
    'Miami',
    'Virginia Beach',
    'Oakland',
    'Minneapolis',
    'Tulsa',
    'Tampa',
    'Arlington',
    'New Orleans',
    'Wichita',
    'Cleveland',
    'Bakersfield',
    'Aurora',
    'Anaheim',
    'Honolulu',
    'Santa Ana',
    'Corpus Christi',
    'Riverside',
    'Lexington',
    'Stockton',
    'Henderson',
    'Saint Paul',
    'St. Louis',
    'Cincinnati',
    'Pittsburgh',
  ],
};
